# Generated by Django 2.1.7 on 2019-05-02 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='completeNum',
        ),
        migrations.RemoveField(
            model_name='project',
            name='incompleteNum',
        ),
    ]
