# Generated by Django 2.1.7 on 2019-05-02 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190502_0706'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('taskTitle',)},
        ),
        migrations.RemoveField(
            model_name='project',
            name='taskList',
        ),
        migrations.AddField(
            model_name='task',
            name='proj',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Project'),
        ),
    ]
