# Generated by Django 2.1.7 on 2019-05-02 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190502_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='proj',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='users.Project'),
        ),
    ]
