# Generated by Django 2.1.7 on 2019-05-02 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190502_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='completion',
            field=models.BooleanField(default=False),
        ),
    ]
