# Generated by Django 2.1.7 on 2019-05-02 05:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectTitle', models.CharField(max_length=100)),
                ('incompleteNum', models.IntegerField(default=0)),
                ('completeNum', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='task',
            name='author',
        ),
        migrations.RemoveField(
            model_name='task',
            name='date_due',
        ),
        migrations.AddField(
            model_name='task',
            name='completion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='taskList',
            field=models.ManyToManyField(to='tasks.Task'),
        ),
    ]
